version: "3"

services: 
  # pgdb: 
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   environment: 
  #     - POSTGRES_PASSWORD:password
  #   volumes: 
  #     - ./database/pg-data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"

